/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSyncV2ChangesRouteImport } from './routes/api/sync/v2/changes'
import { Route as ApiSyncV2MutationsRouteImport } from './routes/api/sync/v2/mutations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncV2ChangesRoute = ApiSyncV2ChangesRouteImport.update({
  id: '/api/sync/v2/changes',
  path: '/api/sync/v2/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncV2MutationsRoute = ApiSyncV2MutationsRouteImport.update({
  id: '/api/sync/v2/mutations',
  path: '/api/sync/v2/mutations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/v2/changes': typeof ApiSyncV2ChangesRoute
  '/api/sync/v2/mutations': typeof ApiSyncV2MutationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/v2/changes': typeof ApiSyncV2ChangesRoute
  '/api/sync/v2/mutations': typeof ApiSyncV2MutationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/v2/changes': typeof ApiSyncV2ChangesRoute
  '/api/sync/v2/mutations': typeof ApiSyncV2MutationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/api/health'
    | '/api/auth/$'
    | '/api/sync/v2/changes'
    | '/api/sync/v2/mutations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/api/health'
    | '/api/auth/$'
    | '/api/sync/v2/changes'
    | '/api/sync/v2/mutations'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/api/health'
    | '/api/auth/$'
    | '/api/sync/v2/changes'
    | '/api/sync/v2/mutations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncV2ChangesRoute: typeof ApiSyncV2ChangesRoute
  ApiSyncV2MutationsRoute: typeof ApiSyncV2MutationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/v2/changes': {
      id: '/api/sync/v2/changes'
      path: '/api/sync/v2/changes'
      fullPath: '/api/sync/v2/changes'
      preLoaderRoute: typeof ApiSyncV2ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/v2/mutations': {
      id: '/api/sync/v2/mutations'
      path: '/api/sync/v2/mutations'
      fullPath: '/api/sync/v2/mutations'
      preLoaderRoute: typeof ApiSyncV2MutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncV2ChangesRoute: ApiSyncV2ChangesRoute,
  ApiSyncV2MutationsRoute: ApiSyncV2MutationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
